name: Listing S3 buckts

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }} 
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List S3 buckets
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 ls

      - name: Say Hello
        run: echo "Hello World from ${{ github.repository }}"
